version: "3.4"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=tdrive
      - POSTGRES_USER=tdrive
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tdrive"]
      interval: 10s
      timeout: 2s
      retries: 5

  node_create_user:
    build: &backend_docker_build
      context: .
      dockerfile: docker/tdrive-node/Dockerfile
      target: production
    environment: &backend_env_vars
      - DEV=dev
      - ACCOUNTS_TYPE=internal
      - DB_DRIVER=postgres
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_DBNAME=tdrive
      - DB_POSTGRES_USERNAME=tdrive
      - DB_POSTGRES_PASSWORD=secret
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_USE_SSL=false
      - PUBSUB_TYPE=local
      - SEARCH_DRIVER=mongodb
      - STORAGE_DRIVER=local
      - STORAGE_LOCAL_PATH=/tmp/tdrive
      - ENABLE_FEATURE_ANTIVIRUS=false
      - DIAG_PROBE_SECRET=diag-secret

    command: /usr/src/app/bin/twake-cli dev set_local_user a@b.com aaaaaaaa
    volumes: &backend_volumes
      - ./backend/node/profiles:/usr/src/app/profiles
      - ./backend/node/src:/usr/src/app/src
    depends_on:
      postgres:
        condition: service_healthy

  node:
    build: *backend_docker_build
    ports:
      - 4000:4000
      - 9229:9229
    environment: *backend_env_vars
    healthcheck:
      test: curl --fail 'http://localhost:4000/diagnostics/t/ready?secret=diag-secret'
    volumes: *backend_volumes
    depends_on:
      postgres:
        condition: service_healthy
      node_create_user:
        condition: service_completed_successfully

  frontend:
    build:
      context: .
      dockerfile: docker/tdrive-frontend/Dockerfile
    container_name: tdrive-frontend
    environment:
      - DEV=production
      - SSL_CERTS=off
      - NODE_HOST=http://node:4000
    ports:
      - "8080:80"
    depends_on:
      node:
        condition: service_healthy
    volumes:
      - ./docker-data/logs/nginx/:/var/log/nginx
      - ./docker-data/letsencrypt/:/etc/letsencrypt/
      - ./docker-data/drive-preview/:/tdrive-core/web/medias/
      - ./docker-data/uploads/:/tdrive-core/web/upload/
      - ./docker-data/ssl:/etc/nginx/ssl
